"""empty message

Revision ID: 7a9730258c78
Revises: 0911c2430078
Create Date: 2021-04-07 17:05:05.600858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a9730258c78'
down_revision = '0911c2430078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent', sa.Column('son_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'parent', 'person', ['son_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parent', type_='foreignkey')
    op.drop_column('parent', 'son_id')
    # ### end Alembic commands ###
